/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.VendaDAO;
import DTO.VendaDTO;
import java.awt.Component;
import java.awt.MenuItem;
import java.awt.Point;
import java.awt.event.KeyEvent;
import static java.lang.System.out;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.util.SimpleAnnotationValueVisitor14;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author franc
 */
public class InicialVIEW extends javax.swing.JFrame {

    /**
     * Creates new form InicialVIEW
     */
    public InicialVIEW() {
        initComponents();
        ListarVendasHoje();
        ListarVendasGeral();
        MostrarData(); 
        ListarAnosMesesDias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popTest = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        comboTipoPag = new javax.swing.JComboBox<>();
        txtVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFinalizarVenda = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboTipoPag1 = new javax.swing.JComboBox<>();
        txtValor1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtVenda1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdVenda1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnAtualizarVenda = new javax.swing.JButton();
        btnExcluirVenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQtdVendas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMediaValor = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        txtDinheiro = new javax.swing.JTextField();
        txtPix = new javax.swing.JTextField();
        txtDebito = new javax.swing.JTextField();
        txtCredito = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtOutros = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendasGeral = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtIdVenda2 = new javax.swing.JTextField();
        txtVenda2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDataHora2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        comboTipoPag2 = new javax.swing.JComboBox<>();
        btnAtualizarVenda2 = new javax.swing.JButton();
        btnExcluirVenda2 = new javax.swing.JButton();
        btnEstatisticasTudo = new javax.swing.JButton();
        comboEstatisticasAno = new javax.swing.JComboBox<>();
        comboEstatisticasMes = new javax.swing.JComboBox<>();
        comboEstatisticasDia = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtData2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtQtVendas2 = new javax.swing.JLabel();
        txtValorTotal2 = new javax.swing.JLabel();
        txtMedia2 = new javax.swing.JLabel();
        txtOutros2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtDinheiro2 = new javax.swing.JTextField();
        txtPix2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtDebito2 = new javax.swing.JTextField();
        txtCredito2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        popTest.setEnabled(false);
        popTest.setName("impressão"); // NOI18N

        jMenuItem1.setText("jMenuItem1");
        popTest.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        comboTipoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Debito", "Credito", "Outros" }));
        comboTipoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPagActionPerformed(evt);
            }
        });
        comboTipoPag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboTipoPagKeyPressed(evt);
            }
        });

        txtVenda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtVendaInputMethodTextChanged(evt);
            }
        });
        txtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendaActionPerformed(evt);
            }
        });
        txtVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVendaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVendaKeyTyped(evt);
            }
        });

        jLabel1.setText("Valor:");

        jLabel2.setText("Venda:");

        btnFinalizarVenda.setText("Finalizar Venda");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });
        btnFinalizarVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFinalizarVendaKeyPressed(evt);
            }
        });

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data e Hora", "Venda", "Valor", "Tipo de Pagamento"
            }
        ));
        tabelaVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaVendas.setGridColor(new java.awt.Color(51, 51, 51));
        tabelaVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendasMouseClicked(evt);
            }
        });
        tabelaVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaVendasKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaVendas);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Vendas");
        jLabel4.setToolTipText("");

        comboTipoPag1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Debito", "Credito", "Outros" }));
        comboTipoPag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPag1ActionPerformed(evt);
            }
        });

        txtValor1.setToolTipText("");

        jLabel5.setText("Valor:");

        jLabel6.setText("Venda:");

        txtVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenda1ActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");

        txtIdVenda1.setEnabled(false);
        txtIdVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVenda1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Data e Hora:");

        txtDataHora.setToolTipText("");
        txtDataHora.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nova Venda");
        jLabel9.setToolTipText("");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAtualizarVenda.setText("Atualizar Venda");
        btnAtualizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarVendaActionPerformed(evt);
            }
        });

        btnExcluirVenda.setText("Excluir Venda");
        btnExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVendaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        txtData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtData.setText("00/00/2022");

        jLabel10.setText("Total:");

        txtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValorTotal.setText("R$ 00,00");

        jLabel12.setText("Qt. Vendas:");

        txtQtdVendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQtdVendas.setText("00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Dados selecionados");

        jLabel11.setText("Média:");

        txtMediaValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMediaValor.setText("00");

        jLabel19.setText("Dinheiro:");

        jLabel20.setText("Pix:");

        jLabel21.setText("Debito:");

        jLabel22.setText("Credito:");

        txtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValorMouseClicked(evt);
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        txtDinheiro.setEnabled(false);

        txtPix.setEnabled(false);

        txtDebito.setEnabled(false);

        txtCredito.setEnabled(false);
        txtCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditoActionPerformed(evt);
            }
        });

        jLabel23.setText("Outros:");

        txtOutros.setEnabled(false);
        txtOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(163, 163, 163))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(9, 9, 9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorTotal)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMediaValor))
                            .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(5, 5, 5)
                                .addComponent(txtQtdVendas))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(85, 85, 85)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel21))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                .addComponent(txtCredito)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPix))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 3, Short.MAX_VALUE)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(btnAtualizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(txtValor1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboTipoPag1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                                .addComponent(btnExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(151, 151, 151)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataHora)))))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipoPag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtQtdVendas))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtValorTotal)
                            .addComponent(jLabel11)
                            .addComponent(txtMediaValor))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Inicial", jPanel1);

        tabelaVendasGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Data e Hora", "Venda", "Valor", "Tipo de Pagamento"
            }
        ));
        tabelaVendasGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendasGeralMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVendasGeral);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Dados selecionados");

        txtIdVenda2.setEnabled(false);
        txtIdVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVenda2ActionPerformed(evt);
            }
        });

        txtVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenda2ActionPerformed(evt);
            }
        });

        jLabel15.setText("ID:");

        jLabel16.setText("Venda:");

        jLabel17.setText("Data e Hora:");

        txtDataHora2.setToolTipText("");
        txtDataHora2.setEnabled(false);

        jLabel18.setText("Valor:");

        txtValor2.setToolTipText("");

        comboTipoPag2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Debito", "Credito", "Outros" }));
        comboTipoPag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPag2ActionPerformed(evt);
            }
        });

        btnAtualizarVenda2.setText("Atualizar Venda");
        btnAtualizarVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarVenda2ActionPerformed(evt);
            }
        });

        btnExcluirVenda2.setText("Excluir Venda");
        btnExcluirVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVenda2ActionPerformed(evt);
            }
        });

        btnEstatisticasTudo.setText("Tudo");
        btnEstatisticasTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasTudoActionPerformed(evt);
            }
        });

        comboEstatisticasAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano" }));
        comboEstatisticasAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstatisticasAnoActionPerformed(evt);
            }
        });

        comboEstatisticasMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês" }));
        comboEstatisticasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstatisticasMesActionPerformed(evt);
            }
        });

        comboEstatisticasDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia" }));
        comboEstatisticasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstatisticasDiaActionPerformed(evt);
            }
        });

        jLabel24.setText("Data:");

        txtData2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtData2.setText("00/00/0000");

        jLabel26.setText("Qt. Vendas:");

        jLabel27.setText("Valor Total:");

        jLabel28.setText("Media:");

        txtQtVendas2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQtVendas2.setText("000");

        txtValorTotal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValorTotal2.setText("0000,00");

        txtMedia2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMedia2.setText("00,00");

        txtOutros2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOutros2.setEnabled(false);
        txtOutros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutros2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Dinheiro:");

        jLabel33.setText("Pix:");

        txtDinheiro2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDinheiro2.setEnabled(false);

        txtPix2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPix2.setEnabled(false);

        jLabel34.setText("Outros:");

        txtDebito2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDebito2.setEnabled(false);

        txtCredito2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCredito2.setEnabled(false);
        txtCredito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCredito2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Debito:");

        jLabel29.setText("Credito:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorTotal2)
                                    .addComponent(txtQtVendas2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedia2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                        .addGap(113, 113, 113))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPix2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDinheiro2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOutros2)
                                    .addComponent(txtDebito2)
                                    .addComponent(txtCredito2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEstatisticasTudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEstatisticasAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEstatisticasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEstatisticasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAtualizarVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtIdVenda2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboTipoPag2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDataHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEstatisticasTudo)
                        .addComponent(comboEstatisticasAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboEstatisticasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboEstatisticasDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtData2))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtQtVendas2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtValorTotal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtMedia2))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtDinheiro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtPix2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDebito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCredito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtOutros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtDataHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipoPag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtIdVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizarVenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estatisticas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVendaActionPerformed
        ExcluirVenda(); 
        ListarVendasHoje();
        LimparCampos2();
    }//GEN-LAST:event_btnExcluirVendaActionPerformed

    private void btnAtualizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarVendaActionPerformed
        AltererVenda();
        ListarVendasHoje();
        LimparCampos2();
    }//GEN-LAST:event_btnAtualizarVendaActionPerformed

    private void txtIdVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVenda1ActionPerformed

    private void txtVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenda1ActionPerformed

    private void comboTipoPag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPag1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoPag1ActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        EnviarValoresVendas();
        ListarVendasHoje();
        LimparCampos1();
          
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void txtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaActionPerformed

    private void comboTipoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoPagActionPerformed

    private void tabelaVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendasMouseClicked
        CarregarCamposVenda();
    }//GEN-LAST:event_tabelaVendasMouseClicked

    private void txtIdVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVenda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVenda2ActionPerformed

    private void txtVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenda2ActionPerformed

    private void comboTipoPag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPag2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoPag2ActionPerformed

    private void btnAtualizarVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarVenda2ActionPerformed
        AltererVenda2();
        LimparCampos3();
        ListarVendasGeral();
    }//GEN-LAST:event_btnAtualizarVenda2ActionPerformed

    private void btnExcluirVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVenda2ActionPerformed
        ExcluirVenda2();
        LimparCampos3();
        ListarVendasGeral();
    }//GEN-LAST:event_btnExcluirVenda2ActionPerformed

    private void tabelaVendasGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendasGeralMouseClicked
        CarregarCamposVenda2();
    }//GEN-LAST:event_tabelaVendasGeralMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        ListarVendasHoje();
        ListarVendasGeral();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void comboEstatisticasAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstatisticasAnoActionPerformed
        ListarVendasAno();
    }//GEN-LAST:event_comboEstatisticasAnoActionPerformed

    private void txtCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditoActionPerformed
        //System.out.println("Vrau");
    }//GEN-LAST:event_txtCreditoActionPerformed

    private void txtOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutrosActionPerformed

    private void txtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorMouseClicked
        txtValor.selectAll();
    }//GEN-LAST:event_txtValorMouseClicked

    private void txtVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtValor.requestFocus();
            popTest.setVisible(false);
            txtValor.selectAll();
        }else if (evt.getKeyCode()== KeyEvent.VK_CONTROL){
            System.out.println(popTest.getName());
            txtVenda.setText(popTest.getName());
            popTest.setVisible(false);
        }
    }//GEN-LAST:event_txtVendaKeyPressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           comboTipoPag.requestFocus();
        } 
    }//GEN-LAST:event_txtValorKeyPressed

    private void comboTipoPagKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboTipoPagKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           btnFinalizarVenda.requestFocus();
        } 
    }//GEN-LAST:event_comboTipoPagKeyPressed

    private void btnFinalizarVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFinalizarVendaKeyPressed
        EnviarValoresVendas();
        ListarVendasHoje();
        LimparCampos1();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           txtVenda.requestFocus();
        } 
    }//GEN-LAST:event_btnFinalizarVendaKeyPressed

    private void tabelaVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaVendasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE){
            ExcluirVenda(); 
            ListarVendasHoje();
            LimparCampos2();
        }
    }//GEN-LAST:event_tabelaVendasKeyPressed

    private void txtVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendaKeyTyped
        //System.out.println(txtVenda.getText());
        if (evt.getKeyChar()== KeyEvent.VK_ENTER){
            txtValor.requestFocus();
            
        }else{
            if(txtVenda.getText().length() > 1){
                VerificaVenda(txtVenda.getText());
            }else{popTest.setVisible(false);} 
        } 
    }//GEN-LAST:event_txtVendaKeyTyped

    private void txtVendaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtVendaInputMethodTextChanged
        
    }//GEN-LAST:event_txtVendaInputMethodTextChanged

    private void txtOutros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutros2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutros2ActionPerformed

    private void txtCredito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCredito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCredito2ActionPerformed

    private void comboEstatisticasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstatisticasDiaActionPerformed
        ListarVendasDia();
    }//GEN-LAST:event_comboEstatisticasDiaActionPerformed

    private void comboEstatisticasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstatisticasMesActionPerformed
        ListarVendasMes();
    }//GEN-LAST:event_comboEstatisticasMesActionPerformed

    private void btnEstatisticasTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasTudoActionPerformed
        ListarVendasGeral();
    }//GEN-LAST:event_btnEstatisticasTudoActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarVenda;
    private javax.swing.JButton btnAtualizarVenda2;
    private javax.swing.JButton btnEstatisticasTudo;
    private javax.swing.JButton btnExcluirVenda;
    private javax.swing.JButton btnExcluirVenda2;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JComboBox<String> comboEstatisticasAno;
    private javax.swing.JComboBox<String> comboEstatisticasDia;
    private javax.swing.JComboBox<String> comboEstatisticasMes;
    private javax.swing.JComboBox<String> comboTipoPag;
    private javax.swing.JComboBox<String> comboTipoPag1;
    private javax.swing.JComboBox<String> comboTipoPag2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu popTest;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JTable tabelaVendasGeral;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtCredito2;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtData2;
    private javax.swing.JTextField txtDataHora;
    private javax.swing.JTextField txtDataHora2;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextField txtDebito2;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtDinheiro2;
    private javax.swing.JTextField txtIdVenda1;
    private javax.swing.JTextField txtIdVenda2;
    private javax.swing.JLabel txtMedia2;
    private javax.swing.JLabel txtMediaValor;
    private javax.swing.JTextField txtOutros;
    private javax.swing.JTextField txtOutros2;
    private javax.swing.JTextField txtPix;
    private javax.swing.JTextField txtPix2;
    private javax.swing.JLabel txtQtVendas2;
    private javax.swing.JLabel txtQtdVendas;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JLabel txtValorTotal;
    private javax.swing.JLabel txtValorTotal2;
    private javax.swing.JTextField txtVenda;
    private javax.swing.JTextField txtVenda1;
    private javax.swing.JTextField txtVenda2;
    // End of variables declaration//GEN-END:variables
    SimpleDateFormat formatAno = new SimpleDateFormat("yyyy");
    SimpleDateFormat formatMes = new SimpleDateFormat("MM/yyyy");
    SimpleDateFormat formatDia = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatBanco = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    private void VerificaVenda(String entrada){
        
        popTest.show(txtVenda, txtVenda.getX(), txtVenda.getY()-38);

        popTest.removeAll();
        String[] lista = {"impressão", "xerox", "pesquisa", "topo de bolo", "balão", "vela", 
                        "emplastificação", "caneta", "serviço digital", "fone de ouvido","folha de papel",
                        "papel de presente", "sacolinha"};
        
        for(String i:lista){
            System.out.println(entrada);
            if(i.contains(entrada)){
                System.out.println("É esse aqui meno: "+i);
                popTest.setName(i);
                popTest.add(i);
                popTest.setVisible(false);               
            }
        } 
        if(popTest.getComponentCount() == 0){
            popTest.setVisible(false);
        }
        popTest.setVisible(true);
        txtVenda.requestFocus();
   } 
   
    private void LimparCampos1(){
        txtValor.setText("");
        txtVenda.setText("");
    }
    
    private void LimparCampos2(){
        txtIdVenda1.setText("");
        txtDataHora.setText("");
        txtValor1.setText("");
        txtVenda1.setText("");
    }
    
    private void LimparCampos3(){
        txtIdVenda2.setText("");
        txtDataHora2.setText("");
        txtValor2.setText("");
        txtVenda2.setText("");
    }
    
    private void EnviarValoresVendas(){
        String venda;
        String valor;
        String tipo_pag;
        
        venda = txtVenda.getText();
        valor = txtValor.getText().replaceAll(",", ".");
        tipo_pag = comboTipoPag.getSelectedItem().toString();
        
        VendaDTO objvendadto = new VendaDTO();
        objvendadto.setVenda(venda);
        objvendadto.setValor(Float.valueOf(valor).floatValue());
        objvendadto.setTipoPag(tipo_pag);
        
        //System.out.println("venda: "+objvendadto.getVenda());
        //System.out.println("valor: "+objvendadto.getValor());
        //System.out.println("Tipo Pagamento: "+objvendadto.getTipoPag());
        
        VendaDAO objvendadao = new VendaDAO();
        objvendadao.novaVenda(objvendadto);
    }
        
    private void ListarAnosMesesDias(){
        try {
            VendaDAO objvendadao = new VendaDAO();
             
            ArrayList<Date> listaDistintaAnos = objvendadao.listaAnos();
            ArrayList<Date> listaDistintaMeses = objvendadao.listaMeses();
            ArrayList<Date> listaDistintaDias = objvendadao.listaDias();
            
            for (int i = 0; i<listaDistintaAnos.size(); i++){
                comboEstatisticasAno.addItem(formatAno.format(listaDistintaAnos.get(i)));
            }
            for (int i = 0; i<listaDistintaMeses.size(); i++){
                comboEstatisticasMes.addItem(formatMes.format(listaDistintaMeses.get(i)));
            }
            for (int i = 0; i<listaDistintaDias.size(); i++){
                comboEstatisticasDia.addItem(formatDia.format(listaDistintaDias.get(i)));
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarAnos "+erro);
                    
        }
    }
    
    
    
    
    private void CarregarCamposVenda(){
        int setar = tabelaVendas.getSelectedRow();
        txtIdVenda1.setText(tabelaVendas.getModel().getValueAt(setar, 0).toString());
        txtDataHora.setText(tabelaVendas.getModel().getValueAt(setar, 1).toString());
        txtVenda1.setText(tabelaVendas.getModel().getValueAt(setar, 2).toString());
        txtValor1.setText(tabelaVendas.getModel().getValueAt(setar, 3).toString());
        comboTipoPag1.setSelectedItem(tabelaVendas.getModel().getValueAt(setar, 4));
        
    }
    
    private void ExcluirVenda(){
        int id;
        
        id = Integer.parseInt(txtIdVenda1.getText());
        
        VendaDTO objvendadto = new VendaDTO();
        objvendadto.setId(id);
        
        VendaDAO objvendadao = new VendaDAO();
        objvendadao.excluirVenda(objvendadto);
    }
    
    private void AltererVenda(){
        int id;
        String dataHora, venda, tipoPag;
        float valor;
        
        id = Integer.parseInt(txtIdVenda1.getText());
        dataHora = txtDataHora.getText();
        venda = txtVenda1.getText();
        tipoPag = comboTipoPag1.getSelectedItem().toString();
        valor = Float.parseFloat(txtValor1.getText().replaceAll(",", "."));
        
        VendaDTO objvendadto = new VendaDTO();
        objvendadto.setId(id);
        objvendadto.setDataHora(dataHora);
        objvendadto.setTipoPag(tipoPag);
        objvendadto.setValor(valor);
        objvendadto.setVenda(venda);
        
        VendaDAO objvendadao = new VendaDAO();
        objvendadao.alterarVenda(objvendadto);
    }
    
    private void MostrarData(){
        Date dataAtual = new Date();
        DateFormat dfm = DateFormat.getDateInstance(DateFormat.SHORT);
        txtData.setText(dfm.format(dataAtual));
    }
    
    ////////////////////////////////////////////////////////////////////////////
    
    private void CarregarCamposVenda2(){
        int setar = tabelaVendasGeral.getSelectedRow();
        
        txtIdVenda2.setText(tabelaVendasGeral.getModel().getValueAt(setar, 0).toString());
        txtDataHora2.setText(tabelaVendasGeral.getModel().getValueAt(setar, 1).toString());
        txtVenda2.setText(tabelaVendasGeral.getModel().getValueAt(setar, 2).toString());
        txtValor2.setText(tabelaVendasGeral.getModel().getValueAt(setar, 3).toString());
        comboTipoPag2.setSelectedItem(tabelaVendasGeral.getModel().getValueAt(setar, 4));
        
    }
    private void ExcluirVenda2(){
        int id;
        
        id = Integer.parseInt(txtIdVenda2.getText());
        
        VendaDTO objvendadto = new VendaDTO();
        objvendadto.setId(id);
        
        VendaDAO objvendadao = new VendaDAO();
        objvendadao.excluirVenda(objvendadto);
    }
    
    private void AltererVenda2(){
        int id;
        String dataHora, venda, tipoPag;
        float valor;
        
        id = Integer.parseInt(txtIdVenda2.getText());
        dataHora = txtDataHora2.getText();
        venda = txtVenda2.getText();
        tipoPag = comboTipoPag2.getSelectedItem().toString();
        valor = Float.parseFloat(txtValor2.getText().replaceAll(",", "."));
        
        VendaDTO objvendadto = new VendaDTO();
        objvendadto.setId(id);
        objvendadto.setDataHora(dataHora);
        objvendadto.setTipoPag(tipoPag);
        objvendadto.setValor(valor);
        objvendadto.setVenda(venda);
        
        VendaDAO objvendadao = new VendaDAO();
        objvendadao.alterarVenda(objvendadto);
    }
    
    private void ListarVendasHoje(){
        try{
            VendaDAO objvendadao = new VendaDAO();
            Calendar c = Calendar.getInstance();
            
            DefaultTableModel model = (DefaultTableModel) tabelaVendas.getModel();
            model.setNumRows(0);
            //System.out.println(c.get(Calendar.DAY_OF_MONTH) + " " +c.get(Calendar.MONTH)+1 + " " +c.get(Calendar.YEAR));
            
            ArrayList<VendaDTO> lista = objvendadao.pesquisaVenda(c.get(Calendar.DAY_OF_MONTH), c.get(Calendar.MONTH)+1, c.get(Calendar.YEAR));
            
            float valorTotal = 0;
            float mediaValor = 0;
            int qtdVendas = lista.size();

            float credito = 0;
            float debito = 0;
            float dinheiro = 0;
            float pix = 0;
            float outros = 0;

            for(int num = 0; num < lista.size(); num++){
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getDataHora(),
                    lista.get(num).getVenda(),
                    lista.get(num).getValor(),
                    lista.get(num).getTipoPag()
            }); 

            switch (lista.get(num).getTipoPag()) {
                case "Dinheiro" -> dinheiro += lista.get(num).getValor();
                case "Pix" -> pix += lista.get(num).getValor();
                case "Credito" -> credito += lista.get(num).getValor();
                case "Debito" -> debito += lista.get(num).getValor();
                case "Outros" -> outros += lista.get(num).getValor();
            }

            valorTotal += lista.get(num).getValor();
        }  
        mediaValor = valorTotal/qtdVendas;

        txtQtdVendas.setText(String.valueOf(qtdVendas));
        txtValorTotal.setText("R$ "+String.format("%.2f",valorTotal));
        txtMediaValor.setText("R$ "+String.format("%.2f", mediaValor));

        txtDinheiro.setText("R$ "+String.format("%.2f",dinheiro));
        txtPix.setText("R$ "+String.format("%.2f",pix));
        txtCredito.setText("R$ "+String.format("%.2f",credito));
        txtDebito.setText("R$ "+String.format("%.2f",debito));
        txtOutros.setText("R$ "+String.format("%.2f",outros));
            
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarVendasHoje "+erro);
        }
    }
    
    private void ListarVendasDia(){
        try{
            VendaDAO objvendadao = new VendaDAO();
            String data = comboEstatisticasDia.getSelectedItem().toString();
            Date date = formatDia.parse(data);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            
            DefaultTableModel model = (DefaultTableModel) tabelaVendasGeral.getModel();
            model.setNumRows(0);
            //System.out.println(c.get(Calendar.DAY_OF_MONTH) + " " +c.get(Calendar.MONTH)+1 + " " +c.get(Calendar.YEAR));
            
            System.out.println(calendar.get(Calendar.DAY_OF_MONTH)+"  " +calendar.get(Calendar.MONTH) +"  "+ calendar.get(Calendar.YEAR));
            ArrayList<VendaDTO> lista = objvendadao.pesquisaVenda(calendar.get(Calendar.DAY_OF_MONTH), calendar.get(Calendar.MONTH)+1, calendar.get(Calendar.YEAR));
            
            
            CarregarCamposEstatisticos(lista, model, data);
            
        }
        catch (ParseException erro) {
            JOptionPane.showMessageDialog(null, "ListarVendasDia "+erro);
        }
    }
    
    private void ListarVendasMes(){
        try{
            VendaDAO objvendadao = new VendaDAO();
            String data = comboEstatisticasMes.getSelectedItem().toString();
            Date date = formatMes.parse(data);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            
            DefaultTableModel model = (DefaultTableModel) tabelaVendasGeral.getModel();
            model.setNumRows(0);
            //System.out.println(c.get(Calendar.DAY_OF_MONTH) + " " +c.get(Calendar.MONTH)+1 + " " +c.get(Calendar.YEAR));
            
            System.out.println(calendar.get(Calendar.MONTH) +"  "+ calendar.get(Calendar.YEAR));
            ArrayList<VendaDTO> lista = objvendadao.pesquisaVenda(calendar.get(Calendar.MONTH)+1, calendar.get(Calendar.YEAR));
            
            CarregarCamposEstatisticos(lista, model, data);           
        }
        catch (ParseException erro) {
            JOptionPane.showMessageDialog(null, "ListarVendasMes "+erro);
        }
    }
    
    private void ListarVendasAno(){
        try{
            VendaDAO objvendadao = new VendaDAO();
            String data = comboEstatisticasAno.getSelectedItem().toString();
            Date date = formatAno.parse(data);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);
            
            DefaultTableModel model = (DefaultTableModel) tabelaVendasGeral.getModel();
            model.setNumRows(0);
            //System.out.println(c.get(Calendar.DAY_OF_MONTH) + " " +c.get(Calendar.MONTH)+1 + " " +c.get(Calendar.YEAR));
            
            System.out.println(calendar.get(Calendar.YEAR));
            ArrayList<VendaDTO> lista = objvendadao.pesquisaVenda(calendar.get(Calendar.YEAR));
            
            
            CarregarCamposEstatisticos(lista, model, data);           
        }
        catch (ParseException erro) {
            JOptionPane.showMessageDialog(null, "ListarVendasMes "+erro);
        }
    }
    
        private void ListarVendasGeral(){
        try{
            VendaDAO objvendadao = new VendaDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaVendasGeral.getModel();
            model.setNumRows(0);
            
            ArrayList<VendaDTO> lista = objvendadao.pesquisaVenda();
            
            CarregarCamposEstatisticos(lista, model, "Todos as Datas");
            
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarVendas "+erro);
        }
    }
    
    private void CarregarCamposEstatisticos(ArrayList<VendaDTO> lista, DefaultTableModel model, String data){
        float valorTotal = 0;
        float mediaValor = 0;
        int qtdVendas = lista.size();

        float credito = 0;
        float debito = 0;
        float dinheiro = 0;
        float pix = 0;
        float outros = 0;
        
        txtData2.setText(data);  
        
        for(int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
                lista.get(num).getId(),
                lista.get(num).getDataHora(),
                lista.get(num).getVenda(),
                lista.get(num).getValor(),
                lista.get(num).getTipoPag()
            }); 

            switch (lista.get(num).getTipoPag()) {
                case "Dinheiro" -> dinheiro += lista.get(num).getValor();
                case "Pix" -> pix += lista.get(num).getValor();
                case "Credito" -> credito += lista.get(num).getValor();
                case "Debito" -> debito += lista.get(num).getValor();
                case "Outros" -> outros += lista.get(num).getValor();
            }

            valorTotal += lista.get(num).getValor();
        }  
        mediaValor = valorTotal/qtdVendas;

        txtQtVendas2.setText(String.valueOf(qtdVendas));
        txtValorTotal2.setText("R$ "+String.format("%.2f",valorTotal));
        txtMedia2.setText("R$ "+String.format("%.2f", mediaValor));

        txtDinheiro2.setText("R$ "+String.format("%.2f",dinheiro));
        txtPix2.setText("R$ "+String.format("%.2f",pix));
        txtCredito2.setText("R$ "+String.format("%.2f",credito));
        txtDebito2.setText("R$ "+String.format("%.2f",debito));
        txtOutros2.setText("R$ "+String.format("%.2f",outros));
    }
     
}
